# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate_password_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmGenerator(object):
    def setupUi(self, FrmGenerator):
        FrmGenerator.setObjectName("FrmGenerator")
        FrmGenerator.resize(280, 343)
        FrmGenerator.setMinimumSize(QtCore.QSize(280, 343))
        FrmGenerator.setMaximumSize(QtCore.QSize(280, 343))
        self.label = QtWidgets.QLabel(FrmGenerator)
        self.label.setGeometry(QtCore.QRect(10, 5, 71, 16))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnGeneratePassword = QtWidgets.QPushButton(FrmGenerator)
        self.btnGeneratePassword.setGeometry(QtCore.QRect(80, 237, 111, 31))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnGeneratePassword.setFont(font)
        self.btnGeneratePassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGeneratePassword.setStyleSheet("QPushButton {\n"
"background-color: rgb(217, 227, 221);\n"
"border: none;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"border-top: 1px solid #4b4b4b;\n"
"border-left: 1px solid #4b4b4b;\n"
"border-right: 1px solid #4b4b4b;\n"
"border-bottom: 1.5px solid #4b4b4b;\n"
"text-align:center;\n"
"padding-left: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style:solid;\n"
"border-width:2px;\n"
"}")
        self.btnGeneratePassword.setObjectName("btnGeneratePassword")
        self.btnResetList = QtWidgets.QPushButton(FrmGenerator)
        self.btnResetList.setGeometry(QtCore.QRect(10, 200, 75, 23))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        self.btnResetList.setFont(font)
        self.btnResetList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResetList.setStyleSheet("QPushButton {\n"
"background-color: rgb(217, 227, 221);\n"
"border: none;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"border-top: 1px solid #4b4b4b;\n"
"border-left: 1px solid #4b4b4b;\n"
"border-right: 1px solid #4b4b4b;\n"
"border-bottom: 1.5px solid #4b4b4b;\n"
"text-align:center;\n"
"padding-left: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style:solid;\n"
"border-width:2px;\n"
"}")
        self.btnResetList.setObjectName("btnResetList")
        self.lswKeywords = QtWidgets.QListWidget(FrmGenerator)
        self.lswKeywords.setGeometry(QtCore.QRect(10, 60, 261, 131))
        self.lswKeywords.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.lswKeywords.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lswKeywords.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lswKeywords.setObjectName("lswKeywords")
        self.layoutWidget = QtWidgets.QWidget(FrmGenerator)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 262, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtKeyword = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyword.sizePolicy().hasHeightForWidth())
        self.txtKeyword.setSizePolicy(sizePolicy)
        self.txtKeyword.setMinimumSize(QtCore.QSize(0, 20))
        self.txtKeyword.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtKeyword.setToolTip("")
        self.txtKeyword.setInputMask("")
        self.txtKeyword.setMaxLength(30)
        self.txtKeyword.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.txtKeyword.setClearButtonEnabled(True)
        self.txtKeyword.setObjectName("txtKeyword")
        self.horizontalLayout.addWidget(self.txtKeyword)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAddKeyword = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddKeyword.sizePolicy().hasHeightForWidth())
        self.btnAddKeyword.setSizePolicy(sizePolicy)
        self.btnAddKeyword.setMinimumSize(QtCore.QSize(23, 23))
        self.btnAddKeyword.setMaximumSize(QtCore.QSize(23, 23))
        self.btnAddKeyword.setBaseSize(QtCore.QSize(23, 23))
        self.btnAddKeyword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddKeyword.setStyleSheet("QPushButton {\n"
"background-color: rgb(217, 227, 221);\n"
"border: none;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"border-top: 1px solid #4b4b4b;\n"
"border-left: 1px solid #4b4b4b;\n"
"border-right: 1px solid #4b4b4b;\n"
"border-bottom: 1.5px solid #4b4b4b;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style:solid;\n"
"border-width:2px;\n"
"}")
        self.btnAddKeyword.setText("")
        self.btnAddKeyword.setObjectName("btnAddKeyword")
        self.horizontalLayout.addWidget(self.btnAddKeyword)
        self.layoutWidget1 = QtWidgets.QWidget(FrmGenerator)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 320, 92, 16))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setUnderline(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lblLength = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        self.lblLength.setFont(font)
        self.lblLength.setObjectName("lblLength")
        self.horizontalLayout_2.addWidget(self.lblLength)
        self.layoutWidget2 = QtWidgets.QWidget(FrmGenerator)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 280, 270, 33))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtGeneratedPassword = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGeneratedPassword.sizePolicy().hasHeightForWidth())
        self.txtGeneratedPassword.setSizePolicy(sizePolicy)
        self.txtGeneratedPassword.setMinimumSize(QtCore.QSize(225, 31))
        self.txtGeneratedPassword.setMaximumSize(QtCore.QSize(225, 31))
        self.txtGeneratedPassword.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtGeneratedPassword.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.txtGeneratedPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGeneratedPassword.setReadOnly(True)
        self.txtGeneratedPassword.setObjectName("txtGeneratedPassword")
        self.horizontalLayout_3.addWidget(self.txtGeneratedPassword)
        self.btnCopyPassword = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCopyPassword.sizePolicy().hasHeightForWidth())
        self.btnCopyPassword.setSizePolicy(sizePolicy)
        self.btnCopyPassword.setMinimumSize(QtCore.QSize(29, 29))
        self.btnCopyPassword.setMaximumSize(QtCore.QSize(29, 29))
        self.btnCopyPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCopyPassword.setStyleSheet("QPushButton {\n"
"background-color: rgb(217, 227, 221);\n"
"border: none;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"border-top: 1px solid #4b4b4b;\n"
"border-left: 1px solid #4b4b4b;\n"
"border-right: 1px solid #4b4b4b;\n"
"border-bottom: 1.5px solid #4b4b4b;\n"
"text-align:center;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style:solid;\n"
"border-width:2px;\n"
"}")
        self.btnCopyPassword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btnCopyPassword.setText("")
        self.btnCopyPassword.setObjectName("btnCopyPassword")
        self.horizontalLayout_3.addWidget(self.btnCopyPassword)
        self.layoutWidget.raise_()
        self.btnGeneratePassword.raise_()
        self.btnResetList.raise_()
        self.lswKeywords.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()

        self.retranslateUi(FrmGenerator)
        QtCore.QMetaObject.connectSlotsByName(FrmGenerator)

    def retranslateUi(self, FrmGenerator):
        _translate = QtCore.QCoreApplication.translate
        FrmGenerator.setWindowTitle(_translate("FrmGenerator", "Password Generator"))
        self.label.setText(_translate("FrmGenerator", "Palavra-chave:"))
        self.btnGeneratePassword.setText(_translate("FrmGenerator", "Gerar Senha"))
        self.btnResetList.setText(_translate("FrmGenerator", "Limpar Lista"))
        self.lswKeywords.setToolTip(_translate("FrmGenerator", "Lista de palavras-chave"))
        self.txtKeyword.setPlaceholderText(_translate("FrmGenerator", "Digite sua palavra-chave"))
        self.btnAddKeyword.setToolTip(_translate("FrmGenerator", "Adicionar palavra-chave"))
        self.label_2.setText(_translate("FrmGenerator", "Tamanho:"))
        self.lblLength.setText(_translate("FrmGenerator", "00000"))
        self.btnCopyPassword.setToolTip(_translate("FrmGenerator", "Copiar para área\n"
"de transferência"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmGenerator = QtWidgets.QWidget()
    ui = Ui_FrmGenerator()
    ui.setupUi(FrmGenerator)
    FrmGenerator.show()
    sys.exit(app.exec_())
